CREATE TABLE [dbo].[Image] (
	[Id] INT IDENTITY(1,1) NOT NULL,
	[Name] VARCHAR(50) NOT NULL,
	[Data] VARBINARY(MAX) NOT NULL,
	CONSTRAINT [PK_Image] PRIMARY KEY CLUSTERED ( [Id] ),
	CONSTRAINT [NK_Image] UNIQUE NONCLUSTERED ( [Name] )
);
